### ISSUE TITLE
Unable to obtain SRI hash for local resource

### ISSUE THREAD

**Issue by mvantschip** [kindspells/astro-shield#80]
I am rending a server in hybrid mode and setting the Content-Security-Policy in `astro.config.mjs` as follows:

```mjs
sri: {
      hashesModule: sriHashesModule,
      enableMiddleware: true
    },
    securityHeaders: {
      contentSecurityPolicy: {
        cspDirectives: {
          'default-src': "'self'",
          'font-src': "'self'",
          'img-src': "'self'",
          'form-action': "'self'",
          'connect-src': "'self'",
          'frame-ancestors': "'none'",
        }
      }
    }
```
When working in development, I get constant console errors. `astro dev` shows "Unable to obtain SRI hash for local resource", while my web console shows errors alike "The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “style-src 'self' 'hashes' 'hashes' 'hashes'". In addition, I get errors when dynamically loading certain content...

From all these errors, it seems that there is a problem with the SRI hashes, but I am not sure what I am doing wrong.

I setup my sriHashesModule as in the docs:

```mjs
const rootDir = new URL('.', import.meta.url).pathname;
const sriHashesModule = resolve(rootDir, 'src', 'generated', 'sri.mjs');
```

Am I doing something wrong in setting this up?

Many thanks for your work and support!

**Comment by castarco** [comment]
Hi @mvantschip , please excuse me for my late response.

Indeed, computing the SRI hashes in dev mode is a bit of a nightmare because Astro itself (and Vite) do things quite differently. This is to be expected, since they need extra flexibility to make it easy for us to to stuff such as hot reloading, having a "widget" in our site to do some inspection, etc.

My advice here is to rely on some conditionals to apply a slightly different configuration when running in dev mode. Not nice, but for now I can't offer anything better, sorry... maybe in the future I'll come up with a clean solution for this.
